services:
  - type: web
    name: telegram-gif-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
